"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const user_controller_1 = require("../../components/user/user.controller");
const user_service_1 = require("../../components/user/user.service");
const pipe_1 = require("../pipe");
const dto_1 = require("../../components/user/dto");
const task_service_1 = require("../../components/task/task.service");
const task_controller_1 = require("../../components/task/task.controller");
const middlewares_1 = require("../middlewares");
const config_1 = require("../config");
const dto_2 = require("../dto");
exports.router = (0, express_1.Router)();
const userService = new user_service_1.UserService(config_1.envs.jwtSecretKey);
const userController = new user_controller_1.UserController(userService);
const taskService = new task_service_1.TaskService(config_1.envs.jwtSecretKey);
const taskController = new task_controller_1.TaskController(taskService);
exports.router.get('/users/:email', userController.getUser.bind(userController));
exports.router.post('/users', (0, pipe_1.validationPipe)(dto_1.CreateUserDto), userController.addUser.bind(userController));
exports.router.get('/tasks', (0, middlewares_1.authenticateToken)(config_1.envs.jwtSecretKey), (0, pipe_1.validationPipe)(dto_2.PaginationDto, 'query'), taskController.getTask.bind(taskController));
exports.router.post('/tasks', (0, middlewares_1.authenticateToken)(config_1.envs.jwtSecretKey), taskController.addTask.bind(taskController));
